/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-11-05 03:22:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.groupware;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import employee.model.vo.Employee;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("employee.model.vo.Employee");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

   Employee loginEmp = (Employee) session.getAttribute("loginEmp"); //267, 321 사용자 프로필
   String manager = loginEmp.getIdLevel(); //340 줄

   // 521줄 560줄 까지 관리자 메뉴 

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<title>NADO</title>\r\n");
      out.write("<!-- Tell the browser to be responsive to screen width -->\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\" name=\"viewport\">\r\n");
      out.write("<!-- Bootstrap 3.3.7 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/nado/resources/groupware/bower_components/bootstrap/dist/css/bootstrap.min.css\">\r\n");
      out.write("<!-- Font Awesome 사이드 메뉴 앞에 아이콘 생성됨-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/nado/resources/groupware/bower_components/font-awesome/css/font-awesome.min.css\">\r\n");
      out.write("<!-- Ionicons -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/nado/resources/groupware/bower_components/Ionicons/css/ionicons.min.css\">\r\n");
      out.write("<!-- Theme style 전체적인 테마스타일 바뀜 왼쪽 사이드 메뉴도 바뀜-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/nado/resources/groupware/dist/css/AdminLTE.min.css\">\r\n");
      out.write("<!-- AdminLTE Skins. Choose a skin from the css/skins folder instead of downloading all of them to reduce the load. 색상들 변경됨-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/nado/resources/groupware/dist/css/skins/_all-skins.min.css\">\r\n");
      out.write("<!-- bootstrap wysihtml5 - text editor -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/nado/resources/groupware/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("  <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\r\n");
      out.write("  <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("  <![endif]-->\r\n");
      out.write("\r\n");
      out.write("<!-- Google Font -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/nado/resources/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#logout{\r\n");
      out.write("   padding: 0;\r\n");
      out.write("   font-size: small;\r\n");
      out.write("   background: #fff;\r\n");
      out.write("   color: #000;\r\n");
      out.write("   border: none;\r\n");
      out.write("   outline: none;\r\n");
      out.write("   width: 75px;\r\n");
      out.write("   height: 30px;\r\n");
      out.write("   border: 1px solid #4d2497;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#logout:hover{\r\n");
      out.write("   background: #4d2497;\r\n");
      out.write("   color: #fff;\r\n");
      out.write("}\r\n");
      out.write("::selection {\r\n");
      out.write("   background: rgb(199, 190, 232);\r\n");
      out.write("   color: rgb(65, 65, 65);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".treeview a:active {\r\n");
      out.write("   background: #f3f1fa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar-menu>li>a:active {\r\n");
      out.write("   background: #f3f1fa;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body class=\"hold-transition skin-purple-light sidebar-mini\">\r\n");
      out.write("\r\n");
      out.write("   <!-- 공통 -->\r\n");
      out.write("   <div class=\"wrapper\">\r\n");
      out.write("      <header class=\"main-header\">\r\n");
      out.write("\r\n");
      out.write("         <!-- 로고 Logo -->\r\n");
      out.write("         <a href=\"/nado/views/groupware/main.jsp\" class=\"logo\"> <!-- 미니 사이드바 50x50px 미니 로고 mini logo for sidebar mini 50x50 pixels -->\r\n");
      out.write("            <span class=\"logo-mini\"><b>NADO</b></span> <!-- 모바일 디바이스 사이즈 로고 logo for regular state and mobile devices -->\r\n");
      out.write("            <span class=\"logo-lg\"><b>NADO</b>Groupware</span>\r\n");
      out.write("         </a>\r\n");
      out.write("\r\n");
      out.write("         <!-- 일반 사원 페이지 -->\r\n");
      out.write("         ");
 if (manager.equals("G") || manager.equals("M")) { 
      out.write("\r\n");
      out.write("         <!-- 헤더 네비바 Header Navbar: style can be found in header.less -->\r\n");
      out.write("         <nav class=\"navbar navbar-static-top\">\r\n");
      out.write("            <!-- 토글 버튼 Sidebar toggle button-->\r\n");
      out.write("            <a href=\"#\" class=\"sidebar-toggle\" data-toggle=\"push-menu\" role=\"button\"> <span class=\"sr-only\">Toggle navigation</span></a>\r\n");
      out.write("            <div class=\"navbar-custom-menu\">\r\n");
      out.write("               <ul class=\"nav navbar-nav\">\r\n");
      out.write("                  <!-- 쪽지 토글 버튼 Messages: style can be found in dropdown.less-->\r\n");
      out.write("                  <li class=\"dropdown messages-menu\"><a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"> \r\n");
      out.write("                  <i class=\"fa fa-envelope\"></i> <span class=\"label label-success\">4</span></a>\r\n");
      out.write("                     <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li class=\"header\">4개의 새로운 쪽지가 있습니다.</li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                           <!-- 쪽지 토글 눌렀을 때 드롭다운 메뉴 inner menu: contains the actual data -->\r\n");
      out.write("                           <ul class=\"menu\">\r\n");
      out.write("                              <!-- 쪽지 내용 부분 시작 start message -->\r\n");
      out.write("                              <li><a href=\"#\">\r\n");
      out.write("                                    <div class=\"pull-left\">\r\n");
      out.write("                                       <img src=\"/nado/resources/groupware/dist/img/user2-160x160.jpg\" class=\"img-circle\" alt=\"User Image\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <h4>\r\n");
      out.write("                                       보낸사람 이름<small><i class=\"fa fa-clock-o\"></i> 시간</small>\r\n");
      out.write("                                    </h4>\r\n");
      out.write("                                    <p>쪽지 내용</p>\r\n");
      out.write("                              </a></li>\r\n");
      out.write("                              <!-- 쪽지 내용 부분 끝 end message -->\r\n");
      out.write("                              <li><a href=\"#\">\r\n");
      out.write("                                    <div class=\"pull-left\">\r\n");
      out.write("                                       <img src=\"/nado/resources/groupware/dist/img/user3-128x128.jpg\" class=\"img-circle\" alt=\"User Image\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <h4>\r\n");
      out.write("                                       AdminLTE Design Team <small><i class=\"fa fa-clock-o\"></i> 2시간</small>\r\n");
      out.write("                                    </h4>\r\n");
      out.write("                                    <p>Why not buy a new awesome theme?</p>\r\n");
      out.write("                              </a></li>\r\n");
      out.write("                              <li><a href=\"#\">\r\n");
      out.write("                                    <div class=\"pull-left\">\r\n");
      out.write("                                       <img src=\"/nado/resources/groupware/dist/img/user4-128x128.jpg\" class=\"img-circle\" alt=\"User Image\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <h4>\r\n");
      out.write("                                       Developers <small><i class=\"fa fa-clock-o\"></i>오늘</small>\r\n");
      out.write("                                    </h4>\r\n");
      out.write("                                    <p>Why not buy a new awesome theme?</p>\r\n");
      out.write("                              </a></li>\r\n");
      out.write("                              <li><a href=\"#\">\r\n");
      out.write("                                    <div class=\"pull-left\">\r\n");
      out.write("                                       <img src=\"/nado/resources/groupware/dist/img/user3-128x128.jpg\" class=\"img-circle\" alt=\"User Image\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <h4>\r\n");
      out.write("                                       Sales Department <small><i class=\"fa fa-clock-o\"></i>어제</small>\r\n");
      out.write("                                    </h4>\r\n");
      out.write("                                    <p>Why not buy a new awesome theme?</p>\r\n");
      out.write("                              </a></li>\r\n");
      out.write("                              <li><a href=\"#\">\r\n");
      out.write("                                    <div class=\"pull-left\">\r\n");
      out.write("                                       <img src=\"/nado/resources/groupware/dist/img/user4-128x128.jpg\" class=\"img-circle\" alt=\"User Image\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <h4>\r\n");
      out.write("                                       Reviewers <small><i class=\"fa fa-clock-o\"></i> 2일</small>\r\n");
      out.write("                                    </h4>\r\n");
      out.write("                                    <p>Why not buy a new awesome theme?</p>\r\n");
      out.write("                              </a></li>\r\n");
      out.write("                           </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"footer\"><a href=\"#\">모든 쪽지 보기</a></li>\r\n");
      out.write("                     </ul></li>\r\n");
      out.write("                  <!-- 쪽지 드롭다운 메뉴 끝 -->\r\n");
      out.write("\r\n");
      out.write("                  <!-- 알림 토글 버튼 Notifications: style can be found in dropdown.less -->\r\n");
      out.write("                  <li class=\"dropdown notifications-menu\"><a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"> \r\n");
      out.write("                  <i class=\"fa fa-bell\"></i> <span class=\"label label-warning\">10</span></a>\r\n");
      out.write("                     <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li class=\"header\">10개의 알림이 있습니다.</li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                           <!-- 알림 토글 버튼 드롭다운 메뉴 inner menu: contains the actual data -->\r\n");
      out.write("                           <ul class=\"menu\">\r\n");
      out.write("                              <li><a href=\"#\"> <i class=\"fa fa-clipboard text-blue\"></i>\r\n");
      out.write("                                    전자결재가 승인되었습니다.\r\n");
      out.write("                              </a></li>\r\n");
      out.write("                              <li><a href=\"#\"> <i class=\"fa fa-calendar text-yellow\"></i> 오늘의 일정이 있습니다.\r\n");
      out.write("                              </a></li>\r\n");
      out.write("                              <li><a href=\"#\"> <i class=\"fa fa-envelope text-purple\"></i> 새로운 메일이 도착했습니다.\r\n");
      out.write("                              </a></li>\r\n");
      out.write("                              <li><a href=\"#\"> <i class=\"fa fa-table text-green\"></i> 새로운 댓글이 달렸습니다.\r\n");
      out.write("                              </a></li>\r\n");
      out.write("                              <li><a href=\"#\"> <i class=\"fa fa-calendar-check-o text-red\"></i> 예약신청이 반려되었습니다.\r\n");
      out.write("                              </a></li>\r\n");
      out.write("                           </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"footer\"><a href=\"#\">전체 보기</a></li>\r\n");
      out.write("                     </ul></li>\r\n");
      out.write("                  <!-- 알림 토글 메뉴 끝 -->\r\n");
      out.write("\r\n");
      out.write("                  <!-- 채팅 토글 버튼 Control Sidebar Toggle Button -->\r\n");
      out.write("                  <li><a href=\"#\" onclick=\"javascript:chatMain();\"><i class=\"fa fa-wechat\"></i></a></li>\r\n");
      out.write("                  <!-- 채팅 토글 끝 -->\r\n");
      out.write("\r\n");
      out.write("                  <!-- 상단 프로필 영역 User Account: style can be found in dropdown.less -->\r\n");
      out.write("                  <li class=\"dropdown user user-menu\"><a href=\"#\"\r\n");
      out.write("                     class=\"dropdown-toggle\" data-toggle=\"dropdown\"> <!-- 오른쪽 상단 프로필 사진 -->\r\n");
      out.write("                        ");
 if(loginEmp.getMyProfile() != null) { 
      out.write(" \r\n");
      out.write("                        <img src=\"/nado/resources/groupware/employee_profile/");
      out.print( loginEmp.getMyProfile() );
      out.write("\" class=\"user-image\" alt=\"User Image\"> \r\n");
      out.write("                        ");
 } else { 
      out.write(" \r\n");
      out.write("                        <img src=\"/nado/resources/groupware/employee_profile/default-profile.png\" class=\"user-image\" alt=\"User Image\"> \r\n");
      out.write("                        ");
 } 
      out.write(" \r\n");
      out.write("                        <span class=\"hidden-xs\">");
      out.print( loginEmp.getEmpName() );
      out.write("</span>\r\n");
      out.write("                  </a> <!-- 프로필 부분 클릭했을 때 드롭다운 메뉴 -->\r\n");
      out.write("                     <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <!-- 프로필 사진 User image -->\r\n");
      out.write("                        <li class=\"user-header\">\r\n");
      out.write("                           ");
 if(loginEmp.getMyProfile() != null) { 
      out.write(" <img\r\n");
      out.write("                           src=\"/nado/resources/groupware/employee_profile/");
      out.print( loginEmp.getMyProfile() );
      out.write("\"\r\n");
      out.write("                           class=\"img-circle\" alt=\"User Image\"> ");
 } else { 
      out.write(" <img\r\n");
      out.write("                           src=\"/nado/resources/groupware/employee_profile/default-profile.png\"\r\n");
      out.write("                           class=\"img-circle\" alt=\"User Image\"> ");
 } 
      out.write("\r\n");
      out.write("                           <p>");
      out.print( loginEmp.getDeptName() );
      out.write(' ');
      out.print( loginEmp.getJobName() );
      out.write("</p>\r\n");
      out.write("                           <p>");
      out.print( loginEmp.getEmpName() );
      out.write("</p>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <!-- 프로필 수정, 로그아웃 버튼 Menu Footer-->\r\n");
      out.write("                        <li class=\"user-footer\">\r\n");
      out.write("                           <div class=\"pull-left\">\r\n");
      out.write("                              <a href=\"#\" class=\"btn btn-default btn-flat\">프로필</a>\r\n");
      out.write("                           </div>\r\n");
      out.write("                           <div class=\"pull-right\">\r\n");
      out.write("                              <a href=\"#\" class=\"btn btn-default btn-flat\">로그아웃</a>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                     </ul></li>\r\n");
      out.write("                  <!-- 프로필 영역 끝 -->\r\n");
      out.write("               </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("         </nav>\r\n");
      out.write("      </header>\r\n");
      out.write("\r\n");
      out.write("      <!-- 왼쪽 사이드바 시작 Left side column. contains the logo and sidebar -->\r\n");
      out.write("      <aside class=\"main-sidebar\">\r\n");
      out.write("         <!-- sidebar: style can be found in sidebar.less -->\r\n");
      out.write("         <section class=\"sidebar\">\r\n");
      out.write("            <!-- 왼쪽 사이드바 사용자 정보 부분 Sidebar user panel -->\r\n");
      out.write("            <div class=\"user-panel\">\r\n");
      out.write("               <div class=\"user-panel-image\">\r\n");
      out.write("                  ");
 if(loginEmp.getMyProfile() != null) { 
      out.write("\r\n");
      out.write("                  <img src=\"/nado/resources/groupware/employee_profile/");
      out.print( loginEmp.getMyProfile() );
      out.write("\" class=\"img-circle\" alt=\"User Image\">\r\n");
      out.write("                  ");
 } else { 
      out.write("\r\n");
      out.write("                  <img src=\"/nado/resources/groupware/employee_profile/default-profile.png\" class=\"img-circle\" alt=\"User Image\">\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("               </div>\r\n");
      out.write("               <br>\r\n");
      out.write("               <div class=\"user-panel-info\">\r\n");
      out.write("                  <p>");
      out.print( loginEmp.getDeptName() );
      out.write(' ');
      out.print( loginEmp.getJobName() );
      out.write(' ');
      out.print( loginEmp.getEmpName() );
      out.write("</p>\r\n");
      out.write("                  <button id=\"logout\">로그아웃</button>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- 왼쪽 사이드바 검색 기능 부분 search form -->\r\n");
      out.write("            <form action=\"#\" method=\"get\" class=\"sidebar-form\">\r\n");
      out.write("               <div class=\"input-group\">\r\n");
      out.write("                  <input type=\"text\" name=\"q\" class=\"form-control\" placeholder=\"검색\">\r\n");
      out.write("                  <span class=\"input-group-btn\">\r\n");
      out.write("                     <button type=\"submit\" name=\"search\" id=\"search-btn\" class=\"btn btn-flat\">\r\n");
      out.write("                        <i class=\"fa fa-search\"></i>\r\n");
      out.write("                     </button>\r\n");
      out.write("                  </span>\r\n");
      out.write("               </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            <!-- 왼쪽 사이드바 검색 부분 끝 /.search form -->\r\n");
      out.write("\r\n");
      out.write("            <!-- 왼쪽 사이드바 메뉴 시작 sidebar menu: : style can be found in sidebar.less  -->\r\n");
      out.write("            <ul class=\"sidebar-menu\" data-widget=\"tree\">\r\n");
      out.write("\r\n");
      out.write("               <!-- 전자결재 메뉴 -->\r\n");
      out.write("               <li class=\"treeview\"><a href=\"#\"> <i class=\"fa fa-clipboard\"></i> <span>전자결재</span> \r\n");
      out.write("               <span class=\"pull-right-container\"> <i class=\"fa fa-angle-left pull-right\"></i></span></a>\r\n");
      out.write("                  <ul class=\"treeview-menu\">\r\n");
      out.write("                     <li><a href=\"/nado/ealist\"><i class=\"fa fa-angle-right\"></i> 기안하기</a></li>\r\n");
      out.write("                     <li><a href=\"/nado/eatlist\"><i class=\"fa fa-angle-right\"></i> 진행중인 문서</a></li>\r\n");
      out.write("                     <li><a href=\"/nado/eadtlist\"><i class=\"fa fa-angle-right\"></i> 문서함</a></li>\r\n");
      out.write("                     <li><a href=\"/nado/views/groupware/approval/approvalSetting.jsp\"><i class=\"fa fa-angle-right\"></i> 설정</a></li>\r\n");
      out.write("                  </ul></li>\r\n");
      out.write("\r\n");
      out.write("               <!-- 조직도 메뉴 -->\r\n");
      out.write("               <li class=\"notreeview\"><a href=\"/nado/emplist\"> <i class=\"fa fa-group\"></i> <span>조직도</span></a></li>\r\n");
      out.write("\r\n");
      out.write("               <!-- 전자메일 메뉴 -->\r\n");
      out.write("               <li class=\"treeview\"><a href=\"#\"> <i class=\"fa fa-envelope\"></i> <span>전자메일</span> \r\n");
      out.write("               <span class=\"pull-right-container\"> <i class=\"fa fa-angle-left pull-right\"></i></span></a>\r\n");
      out.write("                  <ul class=\"treeview-menu\">\r\n");
      out.write("                     <li><a href=\"/nado/emlist\"><i class=\"fa fa-angle-right\"></i> 메일쓰기</a></li>\r\n");
      out.write("                     <li><a href=\"/nado/views/groupware/email/emailSelfForm.jsp\"><i class=\"fa fa-angle-right\"></i> 내게 쓰기</a></li>\r\n");
      out.write("                     <li><a href=\"/nado/listall\"><i class=\"fa fa-angle-right\"></i> 전체 메일함</a></li>\r\n");
      out.write("                     <li><a href=\"/nado/emsl\"><i class=\"fa fa-angle-right\"></i> 보낸 메일함</a></li>\r\n");
      out.write("                     <li><a href=\"/nado/emr\"><i class=\"fa fa-angle-right\"></i> 받은 메일함</a></li>\r\n");
      out.write("                     <li><a href=\"/nado/esl\"><i class=\"fa fa-angle-right\"></i> 임시 메일함</a></li>\r\n");
      out.write("                     <li><a href=\"/nado/sers\"><i class=\"fa fa-angle-right\"></i> 내게 쓴 메일함</a></li>\r\n");
      out.write("                     <li><a href=\"/nado/emt\"><i class=\"fa fa-angle-right\"></i> 휴지통</a></li>\r\n");
      out.write("                  </ul></li>\r\n");
      out.write("\r\n");
      out.write("               <!-- 캘린더 메뉴 -->\r\n");
      out.write("               <li class=\"notreeview\"><a href=\"/nado/calsa\"> <i class=\"fa fa-calendar-o\"></i><span>캘린더</span></a></li>\r\n");
      out.write("\r\n");
      out.write("               <!-- 게시판 메뉴 -->\r\n");
      out.write("               <li class=\"treeview\"><a href=\"#\"> <i class=\"fa fa-table\"></i><span>게시판</span> \r\n");
      out.write("               <span class=\"pull-right-container\"> <i class=\"fa fa-angle-left pull-right\"></i></span></a>\r\n");
      out.write("                  <ul class=\"treeview-menu\">\r\n");
      out.write("                     <li><a href=\"/nado/nlist.ad\"><i class=\"fa fa-angle-right\"></i> 공지사항</a></li>\r\n");
      out.write("                     <li><a href=\"/nado/blist\"><i class=\"fa fa-angle-right\"></i> 자유게시판</a></li>\r\n");
      out.write("                  </ul></li>\r\n");
      out.write("\r\n");
      out.write("               <!-- 주소록 메뉴 -->\r\n");
      out.write("               <li class=\"treeview\"><a href=\"#\"> <i class=\"fa fa-address-book\"></i> <span>주소록</span> \r\n");
      out.write("               <span class=\"pull-right-container\"> <i class=\"fa fa-angle-left pull-right\"></i></span></a>\r\n");
      out.write("                  <ul class=\"treeview-menu\">\r\n");
      out.write("                     <li><a href=\"#\"><i class=\"fa fa-angle-right\"></i> 주소록 추가</a></li>\r\n");
      out.write("                     <li><a href=\"#\"><i class=\"fa fa-angle-right\"></i> 개인 주소록</a></li>\r\n");
      out.write("                     <li><a href=\"#\"><i class=\"fa fa-angle-right\"></i> 공유 주소록</a></li>\r\n");
      out.write("                  </ul></li>\r\n");
      out.write("\r\n");
      out.write("               <!-- 예약 메뉴 -->\r\n");
      out.write("               <li class=\"treeview\"><a href=\"#\"> <i class=\"fa fa-calendar-check-o\"></i> <span>예약</span> \r\n");
      out.write("               <span class=\"pull-right-container\"> <i class=\"fa fa-angle-left pull-right\"></i></span></a>\r\n");
      out.write("                  <ul class=\"treeview-menu\">\r\n");
      out.write("                     <li><a href=\"#\"><i class=\"fa fa-angle-right\"></i> 예약하기</a></li>\r\n");
      out.write("                     <li><a href=\"#\"><i class=\"fa fa-angle-right\"></i> 예약 조회</a></li>\r\n");
      out.write("                     <li><a href=\"/nado/rvmsa\"><i class=\"fa fa-angle-right\"></i> 나의 예약 조회</a></li>\r\n");
      out.write("                     <li><a href=\"/nado/rvasa.ad\"><i class=\"fa fa-angle-right\"></i> 예약 관리</a></li>\r\n");
      out.write("                  </ul></li>\r\n");
      out.write("               <!-- 마이페이지 메뉴 -->\r\n");
      out.write("               <li class=\"treeview\"><a href=\"#\"> <i class=\"fa fa-user-circle\"></i> <span>마이페이지</span> \r\n");
      out.write("               <span class=\"pull-right-container\"> <i class=\"fa fa-angle-left pull-right\"></i></span></a>\r\n");
      out.write("                  <ul class=\"treeview-menu\">\r\n");
      out.write("                     <li><a href=\"#\"><i class=\"fa fa-angle-right\"></i> 근태 관리</a></li>\r\n");
      out.write("                     <li><a href=\"#\"><i class=\"fa fa-angle-right\"></i> 쪽지함</a></li>\r\n");
      out.write("                     <li><a href=\"#\"><i class=\"fa fa-angle-right\"></i> 내 정보 관리</a></li>\r\n");
      out.write("                  </ul></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("         </section>\r\n");
      out.write("         <!-- 왼쪽 사이드바 메뉴 끝 /.sidebar -->\r\n");
      out.write("      </aside>\r\n");
      out.write("\r\n");
      out.write("      <!-- 가운데 작업 영역 Content Wrapper. Contains page content -->\r\n");
      out.write("      <div class=\"content-wrapper\">\r\n");
      out.write("         <!-- 가운데 작업 영역 헤더 부분 Content Header (Page header) -->\r\n");
      out.write("         <section class=\"content-header\">\r\n");
      out.write("            <h1>\r\n");
      out.write("               홈 <small>home</small>\r\n");
      out.write("            </h1>\r\n");
      out.write("            <ol class=\"breadcrumb\">\r\n");
      out.write("               <li><a href=\"/nado/views/groupware/main.jsp\"><i class=\"fa fa-home\"></i> 홈</a></li>\r\n");
      out.write("               <li class=\"active\">홈</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("         </section>\r\n");
      out.write("\r\n");
      out.write("         <!-- 가운데 메인 작업 영역 Main content -->\r\n");
      out.write("         <section class=\"content\">\r\n");
      out.write("            <h1>사용자 메인페이지</h1>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         </section>\r\n");
      out.write("         <!-- 가운데 메인 작업 영역 끝 /.content -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- 가운데 작업 영역 끝 /.content-wrapper -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- 관리자 페이지 -->\r\n");
      out.write("      ");
 } else if(manager.equals("S")) { 
      out.write("\r\n");
      out.write("      <!-- 관리자 페이지 헤더 네비바 Header Navbar: style can be found in header.less -->\r\n");
      out.write("      <nav class=\"navbar navbar-static-top\">\r\n");
      out.write("         <!-- 관리자 페이지 토글 버튼 Sidebar toggle button-->\r\n");
      out.write("            <a href=\"#\" class=\"sidebar-toggle\" data-toggle=\"push-menu\" role=\"button\"> <span class=\"sr-only\">Toggle navigation</span></a>\r\n");
      out.write("            <div class=\"navbar-custom-menu\">\r\n");
      out.write("               <ul class=\"nav navbar-nav\">\r\n");
      out.write("               <!-- 관리자 페이지 쪽지 토글 버튼 Messages: style can be found in dropdown.less-->\r\n");
      out.write("                  <li class=\"dropdown messages-menu\"><a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"> \r\n");
      out.write("                  <i class=\"fa fa-envelope\"></i> <span class=\"label label-success\">4</span></a>\r\n");
      out.write("                     <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li class=\"header\">4개의 새로운 쪽지가 있습니다.</li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                        <!-- 관리자 페이지 쪽지 토글 눌렀을 때 드롭다운 메뉴 inner menu: contains the actual data -->\r\n");
      out.write("                        <ul class=\"menu\">\r\n");
      out.write("                           <!-- 관리자 페이지 쪽지 내용 부분 시작 start message -->\r\n");
      out.write("                              <li><a href=\"#\">\r\n");
      out.write("                                    <div class=\"pull-left\">\r\n");
      out.write("                                       <img src=\"/nado/resources/groupware/dist/img/user2-160x160.jpg\" class=\"img-circle\" alt=\"User Image\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <h4>\r\n");
      out.write("                                       보낸사람 이름<small><i class=\"fa fa-clock-o\"></i> 시간</small>\r\n");
      out.write("                                    </h4>\r\n");
      out.write("                                    <p>쪽지 내용</p>\r\n");
      out.write("                              </a></li>\r\n");
      out.write("                           <!-- 관리자 페이지 쪽지 내용 부분 끝 end message -->\r\n");
      out.write("                              <li><a href=\"#\">\r\n");
      out.write("                                    <div class=\"pull-left\">\r\n");
      out.write("                                       <img src=\"/nado/resources/groupware/dist/img/user3-128x128.jpg\" class=\"img-circle\" alt=\"User Image\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <h4>\r\n");
      out.write("                                       AdminLTE Design Team <small><i class=\"fa fa-clock-o\"></i> 2시간</small>\r\n");
      out.write("                                    </h4>\r\n");
      out.write("                                    <p>Why not buy a new awesome theme?</p>\r\n");
      out.write("                              </a></li>\r\n");
      out.write("                              <li><a href=\"#\">\r\n");
      out.write("                                    <div class=\"pull-left\">\r\n");
      out.write("                                       <img src=\"/nado/resources/groupware/dist/img/user4-128x128.jpg\" class=\"img-circle\" alt=\"User Image\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <h4>\r\n");
      out.write("                                       Developers <small><i class=\"fa fa-clock-o\"></i>오늘</small>\r\n");
      out.write("                                    </h4>\r\n");
      out.write("                                    <p>Why not buy a new awesome theme?</p>\r\n");
      out.write("                              </a></li>\r\n");
      out.write("                              <li><a href=\"#\">\r\n");
      out.write("                                    <div class=\"pull-left\">\r\n");
      out.write("                                       <img src=\"/nado/resources/groupware/dist/img/user3-128x128.jpg\" class=\"img-circle\" alt=\"User Image\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <h4>\r\n");
      out.write("                                       Sales Department <small><i class=\"fa fa-clock-o\"></i>어제</small>\r\n");
      out.write("                                    </h4>\r\n");
      out.write("                                    <p>Why not buy a new awesome theme?</p>\r\n");
      out.write("                              </a></li>\r\n");
      out.write("                              <li><a href=\"#\">\r\n");
      out.write("                                    <div class=\"pull-left\">\r\n");
      out.write("                                       <img src=\"/nado/resources/groupware/dist/img/user4-128x128.jpg\" class=\"img-circle\" alt=\"User Image\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <h4>\r\n");
      out.write("                                       Reviewers <small><i class=\"fa fa-clock-o\"></i> 2일</small>\r\n");
      out.write("                                    </h4>\r\n");
      out.write("                                    <p>Why not buy a new awesome theme?</p>\r\n");
      out.write("                              </a></li>\r\n");
      out.write("                           </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"footer\"><a href=\"#\">모든 쪽지 보기</a></li>\r\n");
      out.write("                     </ul></li>\r\n");
      out.write("               <!-- 관리자 페이지 쪽지 드롭다운 메뉴 끝 -->\r\n");
      out.write("\r\n");
      out.write("               <!-- 관리자 페이지 알림 토글 버튼 Notifications: style can be found in dropdown.less -->\r\n");
      out.write("               <li class=\"dropdown notifications-menu\"><a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"> <i class=\"fa fa-bell\"></i> <span class=\"label label-warning\">14</span></a>\r\n");
      out.write("                  <ul class=\"dropdown-menu\">\r\n");
      out.write("                     <li class=\"header\">14개의 알림이 있습니다.</li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <!-- 관리자 페이지 알림 토글 버튼 드롭다운 메뉴 inner menu: contains the actual data -->\r\n");
      out.write("                        <ul class=\"menu\">\r\n");
      out.write("                           <li><a href=\"#\"> <i class=\"fa fa-clipboard text-blue\"></i> 전자결재가 승인되었습니다.</a></li>\r\n");
      out.write("                           <li><a href=\"#\"> <i class=\"fa fa-calendar text-yellow\"></i> 오늘의 일정이 있습니다.</a></li>\r\n");
      out.write("                           <li><a href=\"#\"> <i class=\"fa fa-envelope text-purple\"></i> 새로운 메일이 도착했습니다.</a></li>\r\n");
      out.write("                           <li><a href=\"#\"> <i class=\"fa fa-table text-green\"></i> 새로운 댓글이 달렸습니다.</a></li>\r\n");
      out.write("                           <li><a href=\"#\"> <i class=\"fa fa-calendar-check-o text-red\"></i> 예약신청이 반려되었습니다.</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"footer\"><a href=\"#\">전체 보기</a></li>\r\n");
      out.write("                     </ul></li>\r\n");
      out.write("               <!-- 관리자 페이지 알림 토글 메뉴 끝 -->\r\n");
      out.write("\r\n");
      out.write("               <!-- 관리자 페이지 채팅 토글 버튼 Control Sidebar Toggle Button -->\r\n");
      out.write("               <li><a href=\"#\" data-toggle=\"control-sidebar\"> <i class=\"fa fa-wechat\"></i></a></li>\r\n");
      out.write("               <!-- 관리자 페이지 채팅 토글 끝 -->\r\n");
      out.write("\r\n");
      out.write("               <!-- 관리자 페이지 상단 프로필 영역 User Account: style can be found in dropdown.less -->\r\n");
      out.write("               <li class=\"dropdown user user-menu\"><a href=\"#\"\r\n");
      out.write("                  class=\"dropdown-toggle\" data-toggle=\"dropdown\"> <!-- 관리자 페이지 오른쪽 상단 프로필 사진 -->\r\n");
      out.write("                     ");
 if(loginEmp.getMyProfile() != null) { 
      out.write(" \r\n");
      out.write("                     <img src=\"/nado/resources/groupware/employee_profile/");
      out.print( loginEmp.getMyProfile() );
      out.write("\" class=\"user-image\" alt=\"User Image\"> ");
 } else { 
      out.write(" \r\n");
      out.write("                     <img src=\"/nado/resources/groupware/employee_profile/default-profile.png\" class=\"user-image\" alt=\"User Image\"> ");
 } 
      out.write(" <span class=\"hidden-xs\">");
      out.print( loginEmp.getEmpName() );
      out.write("</span>\r\n");
      out.write("               </a> <!-- 관리자 페이지 프로필 부분 클릭했을 때 드롭다운 메뉴 -->\r\n");
      out.write("                  <ul class=\"dropdown-menu\">\r\n");
      out.write("                     <!-- 프로필 사진 User image -->\r\n");
      out.write("                     <li class=\"user-header\">\r\n");
      out.write("                        ");
 if(loginEmp.getMyProfile() != null) { 
      out.write(" \r\n");
      out.write("                        <img src=\"/nado/resources/groupware/employee_profile/");
      out.print( loginEmp.getMyProfile() );
      out.write("\" class=\"img-circle\" alt=\"User Image\"> ");
 } else { 
      out.write(" \r\n");
      out.write("                        <img src=\"/nado/resources/groupware/employee_profile/default-profile.png\" class=\"img-circle\" alt=\"User Image\"> ");
 } 
      out.write("\r\n");
      out.write("                        <p>관리자</p>\r\n");
      out.write("                        <p>");
      out.print( loginEmp.getEmpName() );
      out.write("</p>\r\n");
      out.write("                     </li>\r\n");
      out.write("                     <!-- 관리자 페이지 프로필 수정, 로그아웃 버튼 Menu Footer-->\r\n");
      out.write("                     <li class=\"user-footer\">\r\n");
      out.write("                        <div class=\"pull-left\">\r\n");
      out.write("                           <a href=\"#\" class=\"btn btn-default btn-flat\">프로필</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"pull-right\">\r\n");
      out.write("                           <a href=\"/nado/emplo\" class=\"btn btn-default btn-flat\">로그아웃</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </li>\r\n");
      out.write("                  </ul></li>\r\n");
      out.write("               <!-- 관리자 페이지 프로필 영역 끝 -->\r\n");
      out.write("            </ul>\r\n");
      out.write("         </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("      </header>\r\n");
      out.write("\r\n");
      out.write("      <!-- 관리자 페이지 왼쪽 사이드바 시작 Left side column. contains the logo and sidebar -->\r\n");
      out.write("      <aside class=\"main-sidebar\">\r\n");
      out.write("         <!-- sidebar: style can be found in sidebar.less -->\r\n");
      out.write("         <section class=\"sidebar\">\r\n");
      out.write("            <!-- 관리자 페이지 왼쪽 사이드바 사용자 정보 부분 Sidebar user panel -->\r\n");
      out.write("            <div class=\"user-panel\">\r\n");
      out.write("               <div class=\"user-panel-image\">\r\n");
      out.write("                  ");
 if(loginEmp.getMyProfile() != null) { 
      out.write("\r\n");
      out.write("                  <img src=\"/nado/resources/groupware/employee_profile/");
      out.print( loginEmp.getMyProfile() );
      out.write("\" class=\"img-circle\" alt=\"User Image\">\r\n");
      out.write("                  ");
 } else { 
      out.write("\r\n");
      out.write("                  <img src=\"/nado/resources/groupware/employee_profile/default-profile.png\" class=\"img-circle\" alt=\"User Image\">\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("               </div>\r\n");
      out.write("               <br>\r\n");
      out.write("               <div class=\"user-panel-info\">\r\n");
      out.write("                  <p>\r\n");
      out.write("                     관리자\r\n");
      out.write("                     ");
      out.print( loginEmp.getEmpName() );
      out.write("</p>\r\n");
      out.write("                  <input type=\"button\" id=\"logout\" onclick=\"location='/nado/emplo'\" value=\"로그아웃\">\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- 관리자 페이지 왼쪽 사이드바 검색 기능 부분 search form -->\r\n");
      out.write("            <form action=\"#\" method=\"get\" class=\"sidebar-form\">\r\n");
      out.write("               <div class=\"input-group\">\r\n");
      out.write("                  <input type=\"text\" name=\"q\" class=\"form-control\" placeholder=\"검색\">\r\n");
      out.write("                  <span class=\"input-group-btn\">\r\n");
      out.write("                     <button type=\"submit\" name=\"search\" id=\"search-btn\"\r\n");
      out.write("                        class=\"btn btn-flat\">\r\n");
      out.write("                        <i class=\"fa fa-search\"></i>\r\n");
      out.write("                     </button>\r\n");
      out.write("                  </span>\r\n");
      out.write("               </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            <!-- 관리자 페이지 왼쪽 사이드바 검색 기능 끝 /.search form -->\r\n");
      out.write("\r\n");
      out.write("            <!-- 관리자 메뉴 -->\r\n");
      out.write("            <ul class=\"sidebar-menu\" data-widget=\"tree\">\r\n");
      out.write("               <li><a href=\"/nado/empic.ad\"> <i class=\"fa fa-drivers-license\"></i> <span>사용자승인관리</span></a></li>\r\n");
      out.write("               <li><a href=\"#\"> <i class=\"fa fa-group\"></i> <span>조직도</span></a></li>\r\n");
      out.write("               <li class=\"treeview\"><a href=\"#\"> <i class=\"fa fa-list\"></i><span>게시판 관리</span> <span class=\"pull-right-container\"><i class=\"fa fa-angle-left pull-right\"></i> </span></a>\r\n");
      out.write("                  <ul class=\"treeview-menu\">\r\n");
      out.write("                     <li><a href=\"/nado/nlist.ad\"> <i class=\"fa fa-angle-right\"></i> 공지사항</a></li>\r\n");
      out.write("                     <li><a href=\"/nado/blist\"> <i class=\"fa fa-angle-right\"></i> 자유게시판</a></li>\r\n");
      out.write("                  </ul></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("         </section>\r\n");
      out.write("         <!-- 관리자 메뉴 끝 /.sidebar -->\r\n");
      out.write("\r\n");
      out.write("      </aside>\r\n");
      out.write("\r\n");
      out.write("      <!-- 관리자 페이지 가운데 작업 영역 Content Wrapper. Contains page content -->\r\n");
      out.write("      <div class=\"content-wrapper\">\r\n");
      out.write("         <!-- 관리자 페이지 가운데 작업 영역 헤더 부분 Content Header (Page header) -->\r\n");
      out.write("         <section class=\"content-header\">\r\n");
      out.write("            <h1>\r\n");
      out.write("               홈 <small>home</small>\r\n");
      out.write("            </h1>\r\n");
      out.write("            <ol class=\"breadcrumb\">\r\n");
      out.write("               <li><a href=\"/nado/views/groupware/main.jsp\"><i class=\"fa fa-home\"></i> 홈</a></li>\r\n");
      out.write("               <li class=\"active\">홈</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("         </section>\r\n");
      out.write("\r\n");
      out.write("         <!-- 관리자 페이지 가운데 메인 작업 영역 Main content -->\r\n");
      out.write("         <section class=\"content\">\r\n");
      out.write("            <h1>관리자 메인페이지</h1>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         </section>\r\n");
      out.write("         <!-- 관리자 페이지 가운데 메인 작업 영역 끝 /.content -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- 관리자 페이지 가운데 작업 영역 끝 /.content-wrapper -->\r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <footer class=\"main-footer\">\r\n");
      out.write("         <div class=\"pull-right hidden-xs\">\r\n");
      out.write("            <b>Version</b> 1.0.0\r\n");
      out.write("         </div>\r\n");
      out.write("         <strong>Copyright &copy; 2019 <a href=\"/nado/index.jsp\">NADO Groupware</a>.</strong> All rights reserved.\r\n");
      out.write("      </footer>\r\n");
      out.write("\r\n");
      out.write("      <!-- 공통 -->\r\n");
      out.write("      <!-- 오른쪽 채팅 사이드바 Control Sidebar -->\r\n");
      out.write("      <aside class=\"control-sidebar control-sidebar-dark\" style=\"display: none;\"></aside>\r\n");
      out.write("      <!-- 오른쪽 채팅 사이드바 끝 /.control-sidebar -->\r\n");
      out.write("\r\n");
      out.write("      <!-- Add the sidebar's background. This div must be placed immediately after the control sidebar -->\r\n");
      out.write("      <div class=\"control-sidebar-bg\"></div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <!-- ./wrapper -->\r\n");
      out.write("\r\n");
      out.write("   <!-- jQuery 3 -->\r\n");
      out.write("   <script src=\"/nado/resources/groupware/bower_components/jquery/dist/jquery.min.js\"></script>\r\n");
      out.write("   <!-- jQuery UI 1.11.4 -->\r\n");
      out.write("   <script src=\"/nado/resources/groupware/bower_components/jquery-ui/jquery-ui.min.js\"></script>\r\n");
      out.write("   <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->\r\n");
      out.write("   <script>\r\n");
      out.write("     $.widget.bridge('uibutton', $.ui.button);\r\n");
      out.write("     function chatMain(){\r\n");
      out.write("         window.open(\"/nado/chtm?emp_id=");
      out.print( loginEmp.getEmpId() );
      out.write("\",\"ChatMain\",\"width=410px, height=800px, menubar=no, status=no, toolbar=no\");\r\n");
      out.write("      }\r\n");
      out.write("   </script>\r\n");
      out.write("   <!-- Bootstrap 3.3.7 -->\r\n");
      out.write("   <script src=\"/nado/resources/groupware/bower_components/bootstrap/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("   <!-- Sparkline -->\r\n");
      out.write("   <script src=\"/nado/resources/groupware/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js\"></script>\r\n");
      out.write("   <!-- jQuery Knob Chart -->\r\n");
      out.write("   <script src=\"/nado/resources/groupware/bower_components/jquery-knob/dist/jquery.knob.min.js\"></script>\r\n");
      out.write("   <!-- Bootstrap WYSIHTML5 -->\r\n");
      out.write("   <script src=\"/nado/resources/groupware/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js\"></script>\r\n");
      out.write("   <!-- Slimscroll -->\r\n");
      out.write("   <script src=\"/nado/resources/groupware/bower_components/jquery-slimscroll/jquery.slimscroll.min.js\"></script>\r\n");
      out.write("   <!-- FastClick -->\r\n");
      out.write("   <script src=\"/nado/resources/groupware/bower_components/fastclick/lib/fastclick.js\"></script>\r\n");
      out.write("   <!-- AdminLTE App -->\r\n");
      out.write("   <script src=\"/nado/resources/groupware/dist/js/adminlte.min.js\"></script>\r\n");
      out.write("   <!-- AdminLTE for demo purposes -->\r\n");
      out.write("   <script src=\"/nado/resources/groupware/dist/js/demo.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
