/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-11-02 15:38:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import cloud.model.vo.Cloud;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("cloud.model.vo.Cloud");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

   Cloud loginUser = (Cloud)session.getAttribute("loginUser");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>NADO Cloud</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"description\" content=\"The River template project\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/nado/resources/homepage/css/bootstrap-4.1.2/bootstrap.min.css\">\r\n");
      out.write("<link href=\"/nado/resources/homepage/plugins/font-awesome-4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/nado/resources/homepage/plugins/OwlCarousel2-2.3.4/owl.carousel.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/nado/resources/homepage/plugins/OwlCarousel2-2.3.4/owl.theme.default.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/nado/resources/homepage/plugins/OwlCarousel2-2.3.4/animate.css\">\r\n");
      out.write("<link href=\"/nado/resources/homepage/plugins/jquery-datepicker/jquery-ui.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"/nado/resources/homepage/plugins/colorbox/colorbox.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/nado/resources/homepage/css/main_styles.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/nado/resources/homepage/css/responsive.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/nado/resources/homepage/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".main_nav li:not(:last-of-type){\r\n");
      out.write("   margin-right: 49px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("   <div class=\"super_container\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Header -->\r\n");
      out.write("\r\n");
      out.write("   <header class=\"header\">\r\n");
      out.write("      <div class=\"header_content d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("         <div class=\"logo\"><a href=\"/nado/index.jsp\"><b>NADO</b></a></div>\r\n");
      out.write("         <div class=\"ml-auto d-flex flex-row align-items-center justify-content-start\">\r\n");
      out.write("            <nav class=\"main_nav\">\r\n");
      out.write("               <ul class=\"d-flex flex-row align-items-start justify-content-start\">\r\n");
      out.write("                     <li class=\"active\"><a href=\"/nado/index.jsp\">홈</a></li>\r\n");
      out.write("                     <li><a href=\"/nado/views/homepage/priceGuidanceView.jsp\">상품/가격 안내</a></li>\r\n");
      out.write("                     <li><a href=\"/nado/views/homepage/subscriptView.jsp\">그룹웨어 신청</a></li>\r\n");
      out.write("                     <li><a href=\"/nado/views/homepage/customerSupportView.jsp\">고객지원</a></li>\r\n");
      out.write("                     ");
 if(loginUser != null){ 
      out.write("\r\n");
      out.write("                     <li><a href=\"/nado/views/homepage/passwordCheckView.jsp\">내 정보 수정</a></li>\r\n");
      out.write("                     ");
 if(loginUser.getClId().equals("nado")){ 
      out.write("\r\n");
      out.write("                     <li><a href=\"/nado/views/homepage/cloudAdminMain.jsp\">관리 페이지로 이동</a></li>\r\n");
      out.write("                     ");
}else{ 
      out.write("\r\n");
      out.write("                     <li><a href=\"/nado/views/homepage/companyLogin.jsp\">그룹웨어로 이동</a></li>\r\n");
      out.write("                     ");
} 
      out.write("\r\n");
      out.write("                  </ul>\r\n");
      out.write("               </nav>\r\n");
      out.write("               <div class=\"book_button\">\r\n");
      out.write("                  <a href=\"/nado/cllo\">로그아웃</a>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("               ");
}else{ 
      out.write("\r\n");
      out.write("               </ul>\r\n");
      out.write("               </nav>\r\n");
      out.write("               <div class=\"book_button\">\r\n");
      out.write("                  <a href=\"/nado/views/homepage/login.jsp\">로그인</a>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"book_button\">\r\n");
      out.write("                  <a href=\"/nado/views/homepage/cloudEnroll.jsp\">회원가입</a>\r\n");
      out.write("               </div>\r\n");
      out.write("               ");
}
      out.write("\r\n");
      out.write("               <!-- Hamburger Menu -->\r\n");
      out.write("               <div class=\"hamburger\">\r\n");
      out.write("                  <i class=\"fa fa-bars\" aria-hidden=\"true\"></i>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </header>\r\n");
      out.write("\r\n");
      out.write("      <!-- Menu -->\r\n");
      out.write("\r\n");
      out.write("      <div\r\n");
      out.write("         class=\"menu trans_400 d-flex flex-column align-items-end justify-content-start\">\r\n");
      out.write("         <div class=\"menu_close\">\r\n");
      out.write("            <i class=\"fa fa-times\" aria-hidden=\"true\"></i>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"menu_content\">\r\n");
      out.write("            <nav class=\"menu_nav text-right\">\r\n");
      out.write("               <ul>\r\n");
      out.write("                  <li><a href=\"/nado/index.jsp\">홈</a></li>\r\n");
      out.write("                  <li><a href=\"/nado/views/homepage/priceGuidanceView.jsp\">상품/가격 안내</a></li>\r\n");
      out.write("                  <li><a href=\"/nado/views/homepage/subscriptView.jsp\">그룹웨어 신청</a></li>\r\n");
      out.write("                  <li><a href=\"/nado/views/homepage/customerSupportView.jsp\">고객지원</a></li>\r\n");
      out.write("                  ");
 if(loginUser != null){ 
      out.write("\r\n");
      out.write("                  <li><a href=\"/nado/views/homepage/passwordCheckView.jsp\">내 정보 수정</a></li>\r\n");
      out.write("                  ");
 if(loginUser.getClId().equals("nado")){ 
      out.write("\r\n");
      out.write("                  <li><a href=\"/nado/views/homepage/cloudAdminMain.jsp\">관리페이지로 이동</a></li>\r\n");
      out.write("                  ");
 } else { 
      out.write("\r\n");
      out.write("                  <li><a href=\"/nado/views/homepage/companyLogin.jsp\">그룹웨어로 이동</a></li>\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("                  <br>\r\n");
      out.write("                  <li><a href=\"/nado/cllo\">로그아웃</a></li>\r\n");
      out.write("                  ");
 } else { 
      out.write("\r\n");
      out.write("                  <br>\r\n");
      out.write("                  <li><a href=\"/nado/views/homepage/login.jsp\">로그인</a></li>\r\n");
      out.write("                  <li><a href=\"/nado/views/homepage/cloudEnroll.jsp\">회원가입</a>\r\n");
      out.write("                     ");
 } 
      out.write("\r\n");
      out.write("               </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Home -->\r\n");
      out.write("\r\n");
      out.write("      <div class=\"home\">\r\n");
      out.write("         <div class=\"home_slider_container\">\r\n");
      out.write("            <div class=\"owl-carousel owl-theme home_slider\">\r\n");
      out.write("\r\n");
      out.write("               <!-- Slide -->\r\n");
      out.write("               <div class=\"slide\">\r\n");
      out.write("                  <div class=\"background_image\" style=\"background-image: url(/nado/resources/homepage/images/Mobile-Computer.jpg)\"></div>\r\n");
      out.write("                  <div class=\"home_container\">\r\n");
      out.write("                     <div class=\"container\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                           <div class=\"col\">\r\n");
      out.write("                              <div class=\"home_content text-center\">\r\n");
      out.write("                                 <div class=\"home_title\">NADO Groupware</div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("               <!-- Slide -->\r\n");
      out.write("               <div class=\"slide\">\r\n");
      out.write("                  <div class=\"background_image\" style=\"background-image: url(/nado/resources/homepage/images/qa-business-computer-support.jpg)\"></div>\r\n");
      out.write("                  <div class=\"home_container\">\r\n");
      out.write("                     <div class=\"container\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                           <div class=\"col\">\r\n");
      out.write("                              <div class=\"home_content text-center\">\r\n");
      out.write("                                 <div class=\"home_title\">NADO Groupware</div>\r\n");
      out.write("\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("               <!-- Slide -->\r\n");
      out.write("               <div class=\"slide\">\r\n");
      out.write("                  <div class=\"background_image\" style=\"background-image: url(/nado/resources/homepage/images/1.jpg)\"></div>\r\n");
      out.write("                  <div class=\"home_container\">\r\n");
      out.write("                     <div class=\"container\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                           <div class=\"col\">\r\n");
      out.write("                              <div class=\"home_content text-center\">\r\n");
      out.write("                                 <div class=\"home_title\">NADO Groupware</div>\r\n");
      out.write("\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Home Slider Dots -->\r\n");
      out.write("            <div class=\"home_slider_dots_container\">\r\n");
      out.write("               <div class=\"home_slider_dots\">\r\n");
      out.write("                  <ul id=\"home_slider_custom_dots\" class=\"home_slider_custom_dots d-flex flex-row align-items-start justify-content-start\">\r\n");
      out.write("                     <li class=\"home_slider_custom_dot active\">●</li>\r\n");
      out.write("                     <li class=\"home_slider_custom_dot\">●</li>\r\n");
      out.write("                     <li class=\"home_slider_custom_dot\">●</li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- About -->\r\n");
      out.write("\r\n");
      out.write("      <div class=\"about\">\r\n");
      out.write("         <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("               <!-- About Content -->\r\n");
      out.write("               <div class=\"col-lg-6\">\r\n");
      out.write("                  <div class=\"about_content\">\r\n");
      out.write("                     <div class=\"about_title\">\r\n");
      out.write("                        <h2></h2>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div class=\"about_text\">\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <div>\r\n");
      out.write("                           <img id=\"i_1\" width=\"600\" height=\"300\"\r\n");
      out.write("                              src=\"/nado/resources/homepage/images/전자결재_상세보기.png\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("               <!-- About Images -->\r\n");
      out.write("               <div class=\"col-lg-6\">\r\n");
      out.write("                  <div class=\"about_content\">\r\n");
      out.write("                     <br>\r\n");
      out.write("                     <br>\r\n");
      out.write("                     <div class=\"about_title\" id=\"title11\">\r\n");
      out.write("                        <h2>전자결재</h2>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div class=\"about_text\" id=\"content11\">\r\n");
      out.write("                        <h4>실시간 결재로 빠르게 의사결정을 진행하세요.</h4>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <br>\r\n");
      out.write("                     <br>\r\n");
      out.write("                     <div class=\"about_images d-flex flex-row align-items-center justify-content-between flex-wrap\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <!-- Icon Box -->\r\n");
      out.write("                        <div class=\"col-lg-4 icon_box_col\">\r\n");
      out.write("                           <div class=\"icon_box d-flex flex-column align-items-center justify-content-start text-center\" id=\"1\">\r\n");
      out.write("                              <div class=\"icon_box_icon\">\r\n");
      out.write("                                 <img src=\"/nado/resources/homepage/images/check.svg\" style=\"cursor: pointer\" class=\"svg\" alt=\"https://www.flaticon.com/authors/monkik\">\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"icon_box_title\">\r\n");
      out.write("                                 <h4>전자결재</h4>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Icon Box -->\r\n");
      out.write("                        <div class=\"col-lg-4 icon_box_col\">\r\n");
      out.write("                           <div class=\"icon_box d-flex flex-column align-items-center justify-content-start text-center\" id=\"2\">\r\n");
      out.write("                              <div class=\"icon_box_icon\">\r\n");
      out.write("                                 <img src=\"/nado/resources/homepage/images/envelope.svg\" style=\"cursor: pointer\" class=\"svg\" alt=\"https://www.flaticon.com/authors/monkik\">\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"icon_box_title\">\r\n");
      out.write("                                 <h4>전자메일</h4>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Icon Box -->\r\n");
      out.write("                        <div class=\"col-lg-4 icon_box_col\">\r\n");
      out.write("                           <div class=\"icon_box d-flex flex-column align-items-center justify-content-start text-center\" id=\"3\">\r\n");
      out.write("                              <div class=\"icon_box_icon\">\r\n");
      out.write("                                 <img src=\"/nado/resources/homepage/images/calendar.svg\" style=\"cursor: pointer\" class=\"svg\" alt=\"https://www.flaticon.com/authors/monkik\">\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"icon_box_title\">\r\n");
      out.write("                                 <h4>캘린더</h4>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Icon Box -->\r\n");
      out.write("                        <div class=\"col-lg-4 icon_box_col\">\r\n");
      out.write("                           <div class=\"icon_box d-flex flex-column align-items-center justify-content-start text-center\" id=\"4\">\r\n");
      out.write("                              <div class=\"icon_box_icon\">\r\n");
      out.write("                                 <img src=\"/nado/resources/homepage/images/blackboard.svg\" style=\"cursor: pointer\" class=\"svg\" alt=\"https://www.flaticon.com/authors/monkik\">\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"icon_box_title\">\r\n");
      out.write("                                 <h4>게시판</h4>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Icon Box -->\r\n");
      out.write("                        <div class=\"col-lg-4 icon_box_col\">\r\n");
      out.write("                           <div class=\"icon_box d-flex flex-column align-items-center justify-content-start text-center\" id=\"5\">\r\n");
      out.write("                              <div class=\"icon_box_icon\">\r\n");
      out.write("                                 <img src=\"/nado/resources/homepage/images/network.svg\" style=\"cursor: pointer\" class=\"svg\" alt=\"https://www.flaticon.com/authors/monkik\">\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"icon_box_title\">\r\n");
      out.write("                                 <h4>조직도</h4>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Icon Box -->\r\n");
      out.write("                        <div class=\"col-lg-4 icon_box_col\">\r\n");
      out.write("                           <div class=\"icon_box d-flex flex-column align-items-center justify-content-start text-center\" id=\"6\">\r\n");
      out.write("                              <div class=\"icon_box_icon\">\r\n");
      out.write("                                 <img src=\"/nado/resources/homepage/images/feedback.svg\" style=\"cursor: pointer\" class=\"svg\" alt=\"https://www.flaticon.com/authors/monkik\">\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"icon_box_title\">\r\n");
      out.write("                                 <h4>채팅</h4>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Icon Box -->\r\n");
      out.write("                        <div class=\"col-lg-4 icon_box_col\">\r\n");
      out.write("                           <div class=\"icon_box d-flex flex-column align-items-center justify-content-start text-center\" id=\"7\">\r\n");
      out.write("                              <div class=\"icon_box_icon\">\r\n");
      out.write("                                 <img src=\"/nado/resources/homepage/images/agenda.svg\" style=\"cursor: pointer\" class=\"svg\" alt=\"https://www.flaticon.com/authors/monkik\">\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"icon_box_title\">\r\n");
      out.write("                                 <h4>주소록</h4>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                        <script type=\"text/javascript\">\r\n");
      out.write("                     \r\n");
      out.write("                     $(function(){\r\n");
      out.write("                        $('icon_box_icon').mouseover(function(){\r\n");
      out.write("                           $('icon_box_icon').css('cursor', 'pointer');   \r\n");
      out.write("                        });\r\n");
      out.write("                        \r\n");
      out.write("                        $('#1').click(function(){\r\n");
      out.write("                           $('#i_1').attr('src', '/nado/resources/homepage/images/전자결재_상세보기.png');\r\n");
      out.write("                           $('#title11').html('<h2>전자결재</h2>');\r\n");
      out.write("                           $('#content11').html('<h4>실시간 결재로 빠르게 의사결정을 진행하세요.</h4>');\r\n");
      out.write("                        });\r\n");
      out.write("                        \r\n");
      out.write("                        $('#2').click(function(){\r\n");
      out.write("                           $('#i_1').attr('src', '/nado/resources/homepage/images/전자메일_메일쓰기.png');\r\n");
      out.write("                           $('#title11').html('<h2>전자메일</h2>');\r\n");
      out.write("                           $('#content11').html('<h4>회사 도메인을 사용하는 업무 전용 기업 메일</h4>');\r\n");
      out.write("                        });\r\n");
      out.write("                        \r\n");
      out.write("                        $('#3').click(function(){\r\n");
      out.write("                           $('#i_1').attr('src', '/nado/resources/homepage/images/캘린더_월별 캘린더.png');\r\n");
      out.write("                           $('#title11').html('<h2>캘린더</h2>');\r\n");
      out.write("                           $('#content11').html('<h4>프로젝트 상황이 한눈에 들어오는 일정관리</h4>');\r\n");
      out.write("                        });\r\n");
      out.write("                        \r\n");
      out.write("                        $('#4').click(function(){\r\n");
      out.write("                           $('#i_1').attr('src', '/nado/resources/homepage/images/게시판_공지사항.png');\r\n");
      out.write("                           $('#title11').html('<h2>게시판</h2>');\r\n");
      out.write("                           $('#content11').html('<h4>협업과 정보 공유를 위한 사내 게시판</h4>');\r\n");
      out.write("                        });\r\n");
      out.write("                        \r\n");
      out.write("                        $('#5').click(function(){\r\n");
      out.write("                           $('#i_1').attr('src', '/nado/resources/homepage/images/조직도.png');\r\n");
      out.write("                           $('#title11').html('<h2>조직도</h2>');\r\n");
      out.write("                           $('#content11').html('<h4>조직과 사용자를 더욱 편리하게 생성, 관리하는 인사관리</h4>');\r\n");
      out.write("                        });\r\n");
      out.write("                        \r\n");
      out.write("                        $('#6').click(function(){\r\n");
      out.write("                           $('#i_1').attr('src', '/nado/resources/homepage/images/사용자 메인페이지_채팅.png');\r\n");
      out.write("                           $('#title11').html('<h2>채팅</h2>');\r\n");
      out.write("                           $('#content11').html('<h4>사내 커뮤니케이션을 위한 업무 전용 메신저</h4>');\r\n");
      out.write("                        });\r\n");
      out.write("                        \r\n");
      out.write("                        $('#7').click(function(){\r\n");
      out.write("                           $('#i_1').attr('src', '/nado/resources/homepage/images/주소록_주소록 추가.png');\r\n");
      out.write("                           $('#title11').html('<h2>주소록</h2>');\r\n");
      out.write("                           $('#content11').html('<h4>연락처 공유와 관리가 수월해지는 주소록</h4>');\r\n");
      out.write("                        });\r\n");
      out.write("                        \r\n");
      out.write("                        $('#8').click(function(){\r\n");
      out.write("                           $('#i_1').attr('src', '/nado/resources/homepage/images/gallery_3.jpg');\r\n");
      out.write("                        });\r\n");
      out.write("                        \r\n");
      out.write("                        $('#9').click(function(){\r\n");
      out.write("                           $('#i_1').attr('src', '/nado/resources/homepage/images/gallery_1.jpg');\r\n");
      out.write("                        });\r\n");
      out.write("                     });\r\n");
      out.write("                     \r\n");
      out.write("                  </script>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <!-- Footer -->\r\n");
      out.write("\r\n");
      out.write("         <footer class=\"footer\">\r\n");
      out.write("            <div class=\"footer_content\">\r\n");
      out.write("               <div class=\"container\">\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                     <div class=\"col\">\r\n");
      out.write("                        <div class=\"footer_logo_container text-center\">\r\n");
      out.write("                           <div class=\"footer_logo\">\r\n");
      out.write("                              <a href=\"#\"></a>\r\n");
      out.write("                              <div>NADO</div>\r\n");
      out.write("                              <div>since 2019</div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"row footer_row\">\r\n");
      out.write("\r\n");
      out.write("                     <!-- Newsletter -->\r\n");
      out.write("                     <div class=\"footer_title\">\r\n");
      out.write("                        NADO\r\n");
      out.write("                        <div class=\"footer_list\">\r\n");
      out.write("                           <ul>\r\n");
      out.write("                              <li>(주)나도 경기도 의정부시 대표이사 손혜진</li>\r\n");
      out.write("                              <li>대표전화 1111-1111 사업자등록번호: 211-88-33333 통신판매업 신고번호: 제2019-경기의정부-1111호</li>\r\n");
      out.write("                           </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                     <!-- Footer images -->\r\n");
      out.write("                     <div class=\"col-lg-3\">\r\n");
      out.write("                        <div class=\"certificates d-flex flex-row align-items-start justify-content-lg-between justify-content-start flex-lg-nowrap flex-wrap\">\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"copyright\">\r\n");
      out.write("\r\n");
      out.write("               <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("\r\n");
      out.write("               Copyright &copy;\r\n");
      out.write("               <script>document.write(new Date().getFullYear());</script>\r\n");
      out.write("               All rights reserved | This template is made with \r\n");
      out.write("               <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"#\"target=\"_blank\">NADO</a>\r\n");
      out.write("               <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("            </div>\r\n");
      out.write("         </footer>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <script src=\"/nado/resources/homepage/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("      <script src=\"/nado/resources/homepage/css/bootstrap-4.1.2/popper.js\"></script>\r\n");
      out.write("      <script src=\"/nado/resources/homepage/css/bootstrap-4.1.2/bootstrap.min.js\"></script>\r\n");
      out.write("      <script src=\"/nado/resources/homepage/plugins/greensock/TweenMax.min.js\"></script>\r\n");
      out.write("      <script src=\"/nado/resources/homepage/plugins/greensock/TimelineMax.min.js\"></script>\r\n");
      out.write("      <script src=\"/nado/resources/homepage/plugins/scrollmagic/ScrollMagic.min.js\"></script>\r\n");
      out.write("      <script src=\"/nado/resources/homepage/plugins/greensock/animation.gsap.min.js\"></script>\r\n");
      out.write("      <script src=\"/nado/resources/homepage/plugins/greensock/ScrollToPlugin.min.js\"></script>\r\n");
      out.write("      <script src=\"/nado/resources/homepage/plugins/OwlCarousel2-2.3.4/owl.carousel.js\"></script>\r\n");
      out.write("      <script src=\"/nado/resources/homepage/plugins/easing/easing.js\"></script>\r\n");
      out.write("      <script src=\"/nado/resources/homepage/plugins/progressbar/progressbar.min.js\"></script>\r\n");
      out.write("      <script src=\"/nado/resources/homepage/plugins/parallax-js-master/parallax.min.js\"></script>\r\n");
      out.write("      <script src=\"/nado/resources/homepage/plugins/jquery-datepicker/jquery-ui.js\"></script>\r\n");
      out.write("      <script src=\"/nado/resources/homepage/plugins/colorbox/jquery.colorbox-min.js\"></script>\r\n");
      out.write("      <script src=\"/nado/resources/homepage/js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
