/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-10-28 11:18:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.groupware.manager;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import employee.model.vo.Employee;
import java.util.ArrayList;

public final class employeeApproval_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("employee.model.vo.Employee");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	Employee loginEmp = (Employee) session.getAttribute("loginEmp"); //267, 321 사용자 프로필
	ArrayList<Employee> list = (ArrayList<Employee>)request.getAttribute("list");  //411
	int listSize = list.size();
	
	//217 채팅 모달

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<title>NADO</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".inbox{\r\n");
      out.write("border: none; background: transparent;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\t.popup{\r\n");
      out.write("\tposition:absolute; left:50%; top:50%; transform:translate(-50%, -50%);\r\n");
      out.write("\twidth:1000px; height:650px; box-shadow: 0 0 10px rgba(0,0,0,0.5);\r\n");
      out.write("\tborder-radius: 5px; text-align: center; padding:20px; background:#fff; opacity:0;}\r\n");
      out.write("\t\r\n");
      out.write("\t.pop{\r\n");
      out.write("\t\tdisplay:inline-block;\r\n");
      out.write("\t\twidth: 100px;\r\n");
      out.write("\t\theight: 30px;\r\n");
      out.write("\t\tborder :1px solid black;\r\n");
      out.write("\t\ttext-decoration:none;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.popup:target{\r\n");
      out.write("\topacity :10;\r\n");
      out.write("\tz-index:5;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#pop_left{\r\n");
      out.write("\twidth:50%;\r\n");
      out.write("\theight:550px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#pop_right{\r\n");
      out.write("\twidth:50%;\r\n");
      out.write("\theight:550px;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- Tell the browser to be responsive to screen width -->\r\n");
      out.write("<meta\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\"\r\n");
      out.write("\tname=\"viewport\">\r\n");
      out.write("<!-- Bootstrap 3.3.7 -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/nado/resources/groupware/bower_components/bootstrap/dist/css/bootstrap.min.css\">\r\n");
      out.write("<!-- Font Awesome 사이드 메뉴 앞에 아이콘 생성됨-->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/nado/resources/groupware/bower_components/font-awesome/css/font-awesome.min.css\">\r\n");
      out.write("<!-- Ionicons -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/nado/resources/groupware/bower_components/Ionicons/css/ionicons.min.css\">\r\n");
      out.write("<!-- Theme style 전체적인 테마스타일 바뀜 왼쪽 사이드 메뉴도 바뀜-->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/nado/resources/groupware/dist/css/AdminLTE.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- AdminLTE Skins. Choose a skin from the css/skins\r\n");
      out.write("       folder instead of downloading all of them to reduce the load. 색상들 변경됨-->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/nado/resources/groupware/dist/css/skins/_all-skins.min.css\">\r\n");
      out.write("<!-- Morris chart -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/nado/resources/groupware/bower_components/morris.js/morris.css\">\r\n");
      out.write("<!-- jvectormap -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/nado/resources/groupware/bower_components/jvectormap/jquery-jvectormap.css\">\r\n");
      out.write("<!-- Date Picker -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/nado/resources/groupware/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css\">\r\n");
      out.write("<!-- Daterange picker -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/nado/resources/groupware/bower_components/bootstrap-daterangepicker/daterangepicker.css\">\r\n");
      out.write("<!-- bootstrap wysihtml5 - text editor -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/nado/resources/groupware/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("  <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\r\n");
      out.write("  <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("  <![endif]-->\r\n");
      out.write("\r\n");
      out.write("<!-- Google Font -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"hold-transition skin-purple-light sidebar-mini\">\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t<header class=\"main-header\">\r\n");
      out.write("\t\t\t<!-- 로고 Logo -->\r\n");
      out.write("\t\t\t<a href=\"/nado/views/groupware/main.jsp\" class=\"logo\"> <!-- 미니 사이드바 50x50px 미니 로고 mini logo for sidebar mini 50x50 pixels -->\r\n");
      out.write("\t\t\t\t<span class=\"logo-mini\"><b>NADO</b></span> <!-- 모바일 디바이스 사이즈 로고 logo for regular state and mobile devices -->\r\n");
      out.write("\t\t\t\t<span class=\"logo-lg\"><b>NADO</b>Groupware</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<!-- 관리자 페이지 헤더 네비바 Header Navbar: style can be found in header.less -->\r\n");
      out.write("\t\t\t<nav class=\"navbar navbar-static-top\">\r\n");
      out.write("\t\t\t\t<!-- 관리자 페이지 토글 버튼 Sidebar toggle button-->\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"sidebar-toggle\" data-toggle=\"push-menu\" role=\"button\"> \r\n");
      out.write("\t\t\t\t<span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<div class=\"navbar-custom-menu\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t\t<!-- 관리자 페이지 쪽지 토글 버튼 Messages: style can be found in dropdown.less-->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown messages-menu\"><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"dropdown-toggle\" data-toggle=\"dropdown\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-envelope\"></i> <span class=\"label label-success\">3</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"header\">3개의 새로운 쪽지가 있습니다.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 관리자 페이지 쪽지 토글 눌렀을 때 드롭다운 메뉴 inner menu: contains the actual data -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- 관리자 페이지 쪽지 내용 부분 시작 start message --> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"pull-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"/nado/resources/groupware/dist/img/user2-160x160.jpg\" class=\"img-circle\" alt=\"User Image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h4>보낸사람 이름<small><i class=\"fa fa-clock-o\"></i> 시간</small></h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>쪽지 내용</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- 관리자 페이지 쪽지 내용 부분 끝 end message -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"pull-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"/nado/resources/groupware/dist/img/user3-128x128.jpg\" class=\"img-circle\" alt=\"User Image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h4>AdminLTE Design Team <small><i class=\"fa fa-clock-o\"></i> 2시간</small></h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>Why not buy a new awesome theme?</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"pull-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"/nado/resources/groupware/dist/img/user4-128x128.jpg\" class=\"img-circle\" alt=\"User Image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h4>Developers <small><i class=\"fa fa-clock-o\"></i>오늘</small></h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>Why not buy a new awesome theme?</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"pull-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"/nado/resources/groupware/dist/img/user3-128x128.jpg\" class=\"img-circle\" alt=\"User Image\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h4>Sales Department <small><i class=\"fa fa-clock-o\"></i>어제</small></h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>Why not buy a new awesome theme?</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"pull-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"/nado/resources/groupware/dist/img/user4-128x128.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"img-circle\" alt=\"User Image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<h4>Reviewers <small><i class=\"fa fa-clock-o\"></i> 2일</small></h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p>Why not buy a new awesome theme?</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"footer\"><a href=\"#\">모든 쪽지 보기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li><!-- 관리자 페이지 쪽지 드롭다운 메뉴 끝 -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- 관리자 페이지 알림 토글 버튼 Notifications: style can be found in dropdown.less -->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown notifications-menu\"><a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"> \r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-bell\"></i> <span class=\"label label-warning\">14</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"header\">14개의 알림이 있습니다.</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 관리자 페이지 알림 토글 버튼 드롭다운 메뉴 inner menu: contains the actual data -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\"> <i class=\"fa fa-clipboard text-blue\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t전자결재가 승인되었습니다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"> <i class=\"fa fa-calendar text-yellow\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t오늘의 일정이 있습니다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"> <i class=\"fa fa-envelope text-purple\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t새로운 메일이 도착했습니다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"> <i class=\"fa fa-table text-green\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t새로운 댓글이 달렸습니다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"> <i class=\"fa fa-calendar-check-o text-red\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t예약신청이 반려되었습니다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"footer\"><a href=\"#\">전체 보기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li><!-- 관리자 페이지 알림 토글 메뉴 끝 -->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("<!-- \t\t\t\t\t\t관리자 페이지 채팅 토글 버튼 Control Sidebar Toggle Button -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<li><a href=\"#\" data-toggle=\"control-sidebar\"><i -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\t\tclass=\"fa fa-wechat\"></i></a></li>관리자 페이지 채팅 토글 끝 -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- \t\t\t\t관리자 페이지 채팅 토글 버튼 Control Sidebar Toggle Button -->\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" data-toggle=\"control-sidebar\"><i class=\"fa fa-wechat\"></i></a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- 관리자 페이지 상단 프로필 영역 User Account: style can be found in dropdown.less -->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown user user-menu\"><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"dropdown-toggle\" data-toggle=\"dropdown\"> \r\n");
      out.write("\t\t\t\t\t\t\t<!-- 관리자 페이지 오른쪽 상단 프로필 사진 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/nado/resources/groupware/dist/img/혜진.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"user-image\" alt=\"User Image\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"hidden-xs\">손혜진</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 관리자 페이지 프로필 부분 클릭했을 때 드롭다운 메뉴 -->\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 프로필 사진 User image -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"user-header\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"/nado/resources/groupware/dist/img/혜진.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"img-circle\" alt=\"User Image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>인사부 팀장</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>손혜진</p></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 관리자 페이지 프로필 수정, 로그아웃 버튼 Menu Footer-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"user-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"pull-left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-default btn-flat\">프로필</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-default btn-flat\">로그아웃</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li><!-- 관리자 페이지 프로필 영역 끝 -->\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 관리자 페이지 왼쪽 사이드바 시작 Left side column. contains the logo and sidebar -->\r\n");
      out.write("\t\t<aside class=\"main-sidebar\">\r\n");
      out.write("\t\t\t<!-- sidebar: style can be found in sidebar.less -->\r\n");
      out.write("\t\t\t<section class=\"sidebar\">\r\n");
      out.write("\t\t\t\t<!-- 관리자 페이지 왼쪽 사이드바 사용자 정보 부분 Sidebar user panel -->\r\n");
      out.write("\t\t\t\t<div class=\"user-panel\">\r\n");
      out.write("\t\t\t\t\t<div class=\"user-panel-image\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/nado/resources/groupware/dist/img/혜진.png\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"img-circle\" alt=\"User Image\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<div class=\"user-panel-info\">\r\n");
      out.write("\t\t\t\t\t\t<p>인사부 팀장 손혜진</p>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"logout\">로그아웃</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 관리자 페이지 왼쪽 사이드바 검색 기능 부분 search form -->\r\n");
      out.write("\t\t\t\t<form action=\"#\" method=\"get\" class=\"sidebar-form\">\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"q\" class=\"form-control\" placeholder=\"검색\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"input-group-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" name=\"search\" id=\"search-btn\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-flat\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa fa-search\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<!-- 관리자 페이지 왼쪽 사이드바 검색 기능 끝 /.search form -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t<!-- 관리자 메뉴 -->\r\n");
      out.write("\t\t<ul class=\"sidebar-menu\" data-widget=\"tree\">\r\n");
      out.write("\t\t\t<li><a href=\"/nado/apuser.ad\" style=\"background:#f3f1fa;\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"fa fa-drivers-license\"></i> <span>사용자승인관리</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"> <i class=\"fa fa-group\"></i> <span>조직도</span>\r\n");
      out.write("\t\t\t</a></li>\r\n");
      out.write("\t\t\t<li class=\"treeview\"><a href=\"#\"><i class=\"fa fa-list\"></i><span>게시판\r\n");
      out.write("\t\t\t\t\t\t관리</span> <span class=\"pull-right-container\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-angle-left pull-right\"></i> </span> </a>\r\n");
      out.write("\t\t\t\t<ul class=\"treeview-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-angle-right\"></i>공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-angle-right\"></i>설문조사</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-angle-right\"></i>자유게시판</a></li>\r\n");
      out.write("\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t<li><a href=\"calendar/calendarMonthView.jsp\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"fa fa-clipboard\"></i> <span>전자결재양식</span></a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<!-- 관리자 메뉴 끝 /.sidebar -->\r\n");
      out.write("\t\t</aside>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Content Wrapper. Contains page content  가운데 작업 영역-->\r\n");
      out.write("\t\t<div class=\"content-wrapper\">\r\n");
      out.write("\t\t\t<!-- Content Header (Page header) -->\r\n");
      out.write("\t\t\t<section class=\"content-header\">\r\n");
      out.write("\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t사용자 승인 관리 <small>사용자</small>\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t<ol class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-home\"></i> 홈</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"active\">사용자 승인 관리</li>\r\n");
      out.write("\t\t\t\t</ol>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t<!-- Main content -->\r\n");
      out.write("\t\t\t<section class=\"content\">\r\n");
      out.write("\t\t\t");
 if(listSize >0) {
			for(Employee emp : list){
			
      out.write("\r\n");
      out.write("\t\t\t<form action=\"/nado/empapp.ad\" method=\"post\">\r\n");
      out.write("\t\t\t<div class=\"popup\" id=\"");
      out.print(emp.getEmpId());
      out.write("\">\r\n");
      out.write("\t\t\t<!-- 왼쪽 사용자 입력 사항 -->\r\n");
      out.write("\t\t\t<div id=\"pop_left\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th><label for=\"username\">이름</label></th>\r\n");
      out.write("\t\t\t\t</tr><tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"inbox\" name=\"username\" id=\"username\" value=\"");
      out.print( emp.getEmpName() );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><label for=\"userid\">아이디</label></th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"inbox\"name=\"userid\" id=\"userid\" value=\"");
      out.print( emp.getUserId() );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><label for=\"empno\">생년월일</label></th>\r\n");
      out.write("\t\t\t\t\t</tr><tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"inbox\"name=\"empno\" id=\"empno\" value=\"");
      out.print( emp.getEmpNo() );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><label for=\"email\">이메일</label></th>\r\n");
      out.write("\t\t\t\t\t</tr><tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"inbox\"name=\"email\" id=\"email\" value=\"");
      out.print( emp.getEmail() );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><label for=\"phone\">휴대전화</label></th>\r\n");
      out.write("\t\t\t\t\t</tr><tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"inbox\"name=\"phone\" id=\"phone\" value=\"");
      out.print( emp.getPhone() );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><label for=\"address\">주소</label></th>\r\n");
      out.write("\t\t\t\t\t</tr><tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"inbox\"name=\"address\" id=\"address\" value=\"");
      out.print( emp.getAddress() );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--  오른쪽 관리자 입력 사항 -->\r\n");
      out.write("\t\t\t<div id=\"pop_right\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th><label for=\"empid\">사번</label></th>\r\n");
      out.write("\t\t\t\t</tr><tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"inbox\" name=\"empid\" id=\"empid\" >\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><label for=\"idlevel\">계정구분</label></th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"idlevel\" value=\"G\" >일반사원\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"idlevel\" value=\"M\">관리자\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><label for=\"deptid\">부서</label></th>\r\n");
      out.write("\t\t\t\t\t</tr><tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<select name=\"deptid\" id=\"deptid\">\t\t\r\n");
      out.write("\t\t\t\t\t<option value=\"A1\">관리팀</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"A2\">인사팀</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"B1\">개발1팀</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"B2\">개발2팀</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"C1\">디자인팀</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"D1\">영업팀</option>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><label for=\"jobid\">직책</label></th>\r\n");
      out.write("\t\t\t\t\t</tr><tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<select name=\"jobid\" id=\"jobid\" >\r\n");
      out.write("\t\t\t\t\t<option value=\"J1\">대표이사</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"J2\">부사장</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"J3\">부장</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"J4\">차장</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"J5\">과장</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"J6\">대리</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"J7\">사원</option>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<select name=\"paystep\" id=\"paystep\">\r\n");
      out.write("\t\t\t\t\t<option value=\"1호봉\">1호봉</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"2호봉\">2호봉</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"3호봉\">3호봉</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th><label for=\"state\">상태</label></th>\r\n");
      out.write("\t\t\t\t\t</tr><tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"state\"  value=\"재직\">재직\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"state\"  value=\"휴직\">휴직\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<span class=\"pop\"><button type=\"submit\" style=\"background:none;\">승인</button></span>&nbsp;\r\n");
      out.write("\t\t\t<span class=\"pop\"><button>거절</button></span></div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t");
}} 
      out.write("\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-xs-12\">\r\n");
      out.write("          <div class=\"box\">\r\n");
      out.write("            <div class=\"box-header\">\r\n");
      out.write("              <h3 class=\"box-title\">승인 대기 신청자</h3>\r\n");
      out.write("\t\t\t\t <div class=\"box-body\">\r\n");
      out.write("              <table id=\"example2\" class=\"table table-bordered table-hover\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th>이름</th>\r\n");
      out.write("                  <th>아이디</th>\r\n");
      out.write("                  <th>신청일</th>\r\n");
      out.write("                  <th>승인</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                ");
 if(listSize>0){ 
                for(Employee emp : list){
                
      out.write("\r\n");
      out.write("                <tr> \r\n");
      out.write("                  <td>");
      out.print( emp.getEmpName() );
      out.write("</td>\r\n");
      out.write("                  <td>");
      out.print( emp.getUserId() );
      out.write("</td>\r\n");
      out.write("                  <td>");
      out.print( emp.getHireDate() );
      out.write("</td>                  \r\n");
      out.write("                  <td><a href=\"#");
      out.print(emp.getEmpId() );
      out.write("\"> 확인 후 승인</a></td>\r\n");
      out.write("                  <td><a data-target=\"#");
      out.print(emp.getEmpId() );
      out.write("\" data-toggle=\"modal\"> 확인 후 승인</a></td>\r\n");
      out.write("                  \r\n");
      out.write("                </tr>     \r\n");
      out.write("                ");
}} 
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("              </table>\r\n");
      out.write("             \r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- /.box-body -->\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /.box -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("          <!-- /.box -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.col -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- /.row -->\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal\" id=\"\" tabindex=\"-1\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t<!-- /.content -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.content-wrapper -->\r\n");
      out.write("\t\t<footer class=\"main-footer\">\r\n");
      out.write("\t\t\t<div class=\"pull-right hidden-xs\">\r\n");
      out.write("\t\t\t\t<b>Version</b> 1.0.0\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<strong>Copyright &copy; 2019 <a href=\"/nado/index.jsp\">NADO\r\n");
      out.write("\t\t\t\t\tGroupware</a>.\r\n");
      out.write("\t\t\t</strong> All rights reserved.\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 오른쪽 채팅 사이드바 Control Sidebar -->\r\n");
      out.write("\t\t<aside class=\"control-sidebar control-sidebar-dark\"\r\n");
      out.write("\t\t\tstyle=\"display: none;\"></aside>\r\n");
      out.write("\t\t<!-- 오른쪽 채팅 사이드바 끝 /.control-sidebar -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Add the sidebar's background. This div must be placed\r\n");
      out.write("       immediately after the control sidebar -->\r\n");
      out.write("\t\t<div class=\"control-sidebar-bg\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- ./wrapper -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery 3 -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/nado/resources/groupware/bower_components/jquery/dist/jquery.min.js\"></script>\r\n");
      out.write("\t<!-- jQuery UI 1.11.4 -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/nado/resources/groupware/bower_components/jquery-ui/jquery-ui.min.js\"></script>\r\n");
      out.write("\t<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$.widget.bridge('uibutton', $.ui.button);\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- Bootstrap 3.3.7 -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/nado/resources/groupware/bower_components/bootstrap/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- Morris.js charts -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/nado/resources/groupware/bower_components/raphael/raphael.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/nado/resources/groupware/bower_components/morris.js/morris.min.js\"></script>\r\n");
      out.write("\t<!-- Sparkline -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/nado/resources/groupware/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js\"></script>\r\n");
      out.write("\t<!-- jvectormap -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/nado/resources/groupware/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/nado/resources/groupware/plugins/jvectormap/jquery-jvectormap-world-mill-en.js\"></script>\r\n");
      out.write("\t<!-- jQuery Knob Chart -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/nado/resources/groupware/bower_components/jquery-knob/dist/jquery.knob.min.js\"></script>\r\n");
      out.write("\t<!-- daterangepicker -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/nado/resources/groupware/bower_components/moment/min/moment.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/nado/resources/groupware/bower_components/bootstrap-daterangepicker/daterangepicker.js\"></script>\r\n");
      out.write("\t<!-- datepicker -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/nado/resources/groupware/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap WYSIHTML5 -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/nado/resources/groupware/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js\"></script>\r\n");
      out.write("\t<!-- Slimscroll -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/nado/resources/groupware/bower_components/jquery-slimscroll/jquery.slimscroll.min.js\"></script>\r\n");
      out.write("\t<!-- FastClick -->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"/nado/resources/groupware/bower_components/fastclick/lib/fastclick.js\"></script>\r\n");
      out.write("\t<!-- AdminLTE App -->\r\n");
      out.write("\t<script src=\"/nado/resources/groupware/dist/js/adminlte.min.js\"></script>\r\n");
      out.write("\t<!-- AdminLTE dashboard demo (This is only for demo purposes) -->\r\n");
      out.write("\t<script src=\"/nado/resources/groupware/dist/js/pages/dashboard.js\"></script>\r\n");
      out.write("\t<!-- AdminLTE for demo purposes -->\r\n");
      out.write("\t<script src=\"/nado/resources/groupware/dist/js/demo.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
