/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-11-04 12:24:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.groupware.manager;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import employee.model.vo.Employee;
import java.util.ArrayList;

public final class employeeBeforeApproval_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("employee.model.vo.Employee");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	Employee emp = (Employee)request.getAttribute("empInfo");
	ArrayList<Employee> deptList = (ArrayList<Employee>)request.getAttribute("deptList");
	ArrayList<Employee> jobList = (ArrayList<Employee>)request.getAttribute("jobList");
	ArrayList<Employee> paystep = (ArrayList<Employee>)request.getAttribute("paystep");
	
	String empNo = emp.getEmpNo();
	String birthday = empNo.substring(2, empNo.indexOf("-"));
	String bMonth = birthday.substring(0, 2);
	String bDay = birthday.substring(2, 4);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/nado/resources/css/bootstrap.css\">\r\n");
      out.write("<script src=\"/nado/resources/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("* {\r\n");
      out.write("   margin: 0;\r\n");
      out.write("   padding: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table th{\r\n");
      out.write("   background: #f3f1fa;\r\n");
      out.write("   text-align: center;\r\n");
      out.write("   vertical-align: middle;\r\n");
      out.write("   width: 15%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table td{\r\n");
      out.write("   vertical-align: middle;\r\n");
      out.write("   width: auto;\r\n");
      out.write("}\r\n");
      out.write("button#modifyBtn {\r\n");
      out.write("   border: 1px solid #c7bee8;\r\n");
      out.write("   background: #c7bee8;\r\n");
      out.write("   width: 75px;\r\n");
      out.write("   margin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button#modifyBtn:hover, button#modifyBtn:focus {\r\n");
      out.write("   border: 1px solid #b9abe8;\r\n");
      out.write("   background: #b9abe8;\r\n");
      out.write("   width: 75px;\r\n");
      out.write("   margin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button#closeBtn {\r\n");
      out.write("   border: 1px solid #c7bee8;\r\n");
      out.write("   background: #fff;\r\n");
      out.write("   width: 75px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button#closeBtn:hover, button#closeBtn:focus {\r\n");
      out.write("   border: 1px solid #b9abe8;\r\n");
      out.write("   background: #b9abe8;\r\n");
      out.write("   width: 75px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<form class=\"form-group\" action=\"empapp.ad\" method=\"post\">\r\n");
      out.write("\t\t\t<div class=\"row\" style=\"text-align:center;\">\r\n");
      out.write("\t\t\t\t<table class=\"table table-bordered\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-inline form-group\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th><label class=\"control-label\" for=\"emp_name\">이름 </label></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"emp_name\" name=\"emp_name\" value=\"");
      out.print(emp.getEmpName());
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<th><label class=\"control-label\" for=\"emp_id\">사번 </label></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"emp_id\" name=\"emp_id\">\t\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-inline form-group\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th><label class=\"control-label\" for=\"user_id\">아이디 </label></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"user_id\" name=\"user_id\" value=\"");
      out.print( emp.getUserId() );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<th><label class=\"control-label\" for=\"id_level\">계정구분 </label></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" id=\"id_level\" name=\"id_level\" value=\"M\" checked>일반사원\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" id=\"id_level\" name=\"id_level\" value=\"G\">관리자\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-inline form-group\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th><label class=\"control-label\">생일 </label></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-inline form-group\">\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<input style=\"width:50px;\"type=\"text\" class=\"form-control\" id=\"bMonth\" name=\"bMonth\" value=\"");
      out.print( bMonth );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"bMonth\" class=\"control-label\">월</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input style=\"width:50px;\"type=\"text\" class=\"form-control\" id=\"bDay\" name=\"bDay\" value=\"");
      out.print( bDay );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"bDay\" class=\"control-label\">일</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\t\r\n");
      out.write("\t\t\t\t\t\t\t<th><label class=\"control-label\" for=\"dept_id\">부서 </label></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<select class=\"form-control\" id=\"dept_id\" name=\"dept_id\">\t\r\n");
      out.write("\t\t\t\t\t\t\t");
 for(Employee dList : deptList){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"");
      out.print( dList.getDeptId() );
      out.write('"');
      out.write('>');
      out.print( dList.getDeptName() );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</td>\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-inline form-group\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th><label class=\"control-label\" for=\"email\">이메일 </label></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"email\" name=\"email\" value=\"");
      out.print( emp.getEmail() );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<th><label class=\"control-label\" for=\"job_id\">직책 </label></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"form-control\" id=\"job_id\" name=\"job_id\">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 for(Employee jList : jobList){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print( jList.getJobId() );
      out.write('"');
      out.write('>');
      out.print( jList.getJobName() );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</td>\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-inline form-group\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th><label class=\"control-label\" for=\"phone\">휴대전화 </label></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"phone\" name=\"phone\" value=\"");
      out.print( emp.getPhone() );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<th><label class=\"control-label\" for=\"paystep\">호봉 </label></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"form-control\" id=\"paystep\" name=\"paystep\">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 for(Employee pList : paystep){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print( pList.getPaystep() );
      out.write('"');
      out.write('>');
      out.print( pList.getPaystep() );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-inline form-group\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th><label class=\"control-label\" for=\"address\">주소 </label></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"address\" name=\"address\" value=\"");
      out.print( emp.getAddress() );
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-inline form-group\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t                    <td colspan=\"4\" style=\"text-align: center\"><button id=\"modifyBtn\" type=\"submit\" style=\"cursor: pointer\">승인</button>\r\n");
      out.write("\t                        <button id=\"closeBtn\" onclick=\"window.close();\" style=\"cursor: pointer\">닫기</button></td>\r\n");
      out.write("\t                 \t</tr>\r\n");
      out.write("                 \t</div>\t\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script src=\"/nado/resources/js/bootstrap.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
